FROM node:18

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install --include=dev

COPY frontend/ .

RUN npx vite build

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]